rock.namespace('pong');

pong.constants = {
    LOCALE_EN : 'en',

    RES_ID_I18N_EN : 'RES_ID_I18N_EN',
    RES_ID_MODEL_BALL : 'RES_ID_MODEL_BALL',
    RES_ID_MODEL_RACKET : 'RES_ID_MODEL_RACKET',
    RES_ID_MODEL_WALL : 'RES_ID_MODEL_WALL',
    RES_ID_AUDIO_BOUNCE_BALL : 'RES_ID_AUDIO_BOUNCE_BALL',
    RES_ID_AUDIO_GOAL : 'RES_ID_AUDIO_GOAL',

    BALL_TYPE : 'BALL_TYPE',
    RACKET_TYPE : 'RACKET_TYPE',
    WALL_TYPE : 'WALL_TYPE',
    GOAL_AREA_TYPE : 'GOAL_AREA_TYPE',

    RESOURCE_LOADER_WINDOW : 'RESOURCE_LOADER_WINDOW',
    MAIN_WINDOW : 'MAIN_WINDOW',
    PLAY_AGAIN_WINDOW : 'PLAY_AGAIN_WINDOW',
    PONG_GAME_ENGINE_WINDOW : 'PONG_GAME_ENGINE_WINDOW',

    PONG_RENDERER_CONTEXT : 'PONG_RENDERER_CONTEXT'

};
